import * as Yup from 'yup';

const ErrorSchema = () => {
  const rmsg = ' * Required';

  return Yup.object().shape({
    firstName: Yup.string().required(rmsg),
    lastName: Yup.string().required(rmsg),
    middleInitial: Yup.string(),
    email: Yup.string().email(),
    phone: Yup.string().required(rmsg),
    streetAddress: Yup.string().required(rmsg),
    city: Yup.string().required(rmsg),
    state: Yup.string().length(2).required(rmsg),
    zip: Yup.string().required(rmsg),
    birthdate: Yup.date().required(rmsg),
    social: Yup.string().length(4).required(rmsg),
    entitledToWork: Yup.boolean().required(rmsg),
    youngerThan18: Yup.boolean().required(rmsg),
    convictedFelon: Yup.boolean().required(rmsg),
    felonyExplanation: Yup.string(),
    probation: Yup.boolean().required(rmsg),
    probationEnd: Yup.date(),
    militaryService: Yup.boolean().required(rmsg),
    branch: Yup.string(),
    physicalLimitations: Yup.boolean().required(rmsg),
  /*  position: '',
    referral: '',
    expectedRate: '',
    dateAvailable: '',
    currentlyEmployed: '',
    everApplied: '',
    naturalEssentialsPreviously: '',
    employerWork1: '',
    streetWork1: '',
    cityWork1: '',
    stateWork1: '',
    zipWork1: '',
    phoneWork1: '',
    supervisorWork1: '',
    positionWork1: '',
    startWork1: '',
    endWork1: '',
    payWork1: '',
    reasonWork1: '',
    contactWork1: '',
    employerWork2: '',
    streetWork2: '',
    cityWork2: '',
    stateWork2: '',
    zipWork2: '',
    phoneWork2: '',
    supervisorWork2: '',
    positionWork2: '',
    startWork2: '',
    endWork2: '',
    payWork2: '',
    reasonWork2: '',
    contactWork2: '',
    employerWork3: '',
    streetWork3: '',
    cityWork3: '',
    stateWork3: '',
    zipWork3: '',
    phoneWork3: '',
    supervisorWork3: '',
    positionWork3: '',
    startWork3: '',
    endWork3: '',
    payWork3: '',
    reasonWork3: '',
    contactWork3: '',
    highSchool: '',
    highSchoolYrCompleted: '',
    highSchoolDegree: '',
    highSchoolMajor: '',
    college: '',
    collegeYrCompleted: '',
    collegeDegree: '',
    collegeMajor: '',
    tradeSchool: '',
    tradeSchoolYrCompleted: '',
    tradeSchoolDegree: '',
    tradeSchoolMajor: '',
    other: '',
    otherYrCompleted: '',
    otherDegree: '',
    otherMajor: '',
    specialSkills: '',
    reference1: '',
    reference1Phone: '',
    reference2: '',
    reference2Phone: '',
    reference3: '',
    reference3Phone: '' */
  });
};

export default ErrorSchema;
