const testValues = {
  firstName: 'John',
  lastName: 'Doe',
  middleInitial: 'X',
  email: 'jdoe@anon.com',
  phone: '333-444-5555',
  streetAddress: '123 Electric Ave',
  city: 'Keystone',
  state: 'YU',
  zip: '77889',
  birthdate: '1982-09-08',
  social: '1010',
  entitledToWork: true,
  youngerThan18: false,
  convictedFelon: true,
  felonyExplanation: 'I shot the sheriff, but I did not shoot the deputy',
  probation: true,
  probationEnd: '2222-01-06',
  militaryService: true,
  branch: 'Space Force',
  physicalLimitations: true,
  position: 'Warehouse Associate - Bulk Apothecary',
  referral: 'Saw on Indeed.com',
  expectedRate: '$21.50',
  dateAvailable: '2021-11-01',
  currentlyEmployed: true,
  everApplied: true,
  naturalEssentialsPreviously: true,
  employerWork1: 'Acme',
  streetWork1: '111 Front St',
  cityWork1: 'Farmville',
  stateWork1: 'IJ',
  zipWork1: '88902',
  phoneWork1: '(345) 333-5000',
  supervisorWork1: 'Padriq Phillips',
  positionWork1: 'Corporate Espionage',
  startWork1: '2020-06-01',
  endWork1: '2021-09-30',
  payWork1: '$23.00',
  reasonWork1: 'Left to take care of turtles',
  contactWork1: true,
  employerWork2: 'Boxco',
  streetWork2: '456 Main St',
  cityWork2: 'Atlantis',
  stateWork2: 'TR',
  zipWork2: '88888',
  phoneWork2: '+1 222 444 5555',
  supervisorWork2: 'Kelly Kellog',
  positionWork2: 'Street Magician',
  startWork2: '2017-09-01',
  endWork2: '2019-10-11',
  payWork2: '$50.00/hr',
  reasonWork2: 'Made the wrong rabbit disappear.',
  contactWork2: false,
  employerWork3: 'Startup Inc.',
  streetWork3: '476 Number St',
  cityWork3: 'Gotham',
  stateWork3: 'UI',
  zipWork3: '111222',
  phoneWork3: '+12221111234',
  supervisorWork3: 'Comissioner Gordon',
  positionWork3: 'Hostage',
  startWork3: '2016-03-12',
  endWork3: '2016-03-21',
  payWork3: '100,000/ransom',
  reasonWork3: 'Batman resuced me',
  contactWork3: true,
  highSchool: 'Local City High School',
  highSchoolYrCompleted: '2003',
  highSchoolDegree: 'General Studies',
  highSchoolMajor: 'College Prep',
  college: 'University State College',
  collegeYrCompleted: '2008',
  collegeDegree: 'Bachelor of Arts',
  collegeMajor: 'Dance',
  tradeSchool: 'Madeup County Vocation',
  tradeSchoolYrCompleted: '2011',
  tradeSchoolDegree: 'Assoicates, Performing Arts',
  tradeSchoolMajor: 'Street Magic',
  other: "Dr Lisa's Psychic Camp",
  otherYrCompleted: '2015',
  otherDegree: 'Certificate of completion',
  otherMajor: 'Palm Reading',
  specialSkills: 'Juggling, snake-charming, pig latin.',
  reference1: 'Dr. Phil',
  reference1Phone: '1 (213) 312-1232',
  reference2: 'Dr. Spock',
  reference2Phone: '+12342342342',
  reference3: 'Dr. Doom',
  reference3Phone: '333-2345',
};
